routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'role:client']], function(){
	Route::get('/home', 'HomeController@index')->name('user.home');
});

Route::group(['prefix' => 'backstage'], function(){

	Auth::routes();	

	Route::group(['middleware' => ['auth', 'role:super-admin|admin|cashier']], function(){

		Route::group(['namespace'=>'Admin'], function() {

			Route::get('/', 'DashboardController@index')->name('admin.dashboard');
			Route::get('check_email', 'AdminController@check_email')->name('admin.check_email');
			Route::get('check_username', 'AdminController@check_username')->name('admin.check_username');


			Route::group(['prefix' => 'account'], function(){
				Route::get('/', 'AdminController@account')->name('admin.account');
				Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

		   	Route::group(['prefix'=>'admins','middleware' => 'role:super-admin', 'as' =>'admins.'], function() {
	      		Route::view('/', 'back.admins.index')->name('index');
	      		Route::post('datatable', 'AdminController@datatable')->name('datatable');
  		      	Route::view('create', 'back.admins.create')->name('create');
	      		Route::post('store', 'AdminController@store')->name('store');
	      		Route::get('edit/{id}', 'AdminController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'AdminController@update')->name('update');
	      		Route::post('status', 'AdminController@status')->name('status');
	        	Route::post('/delete', 'AdminController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'cashiers','middleware' => 'role:super-admin|admin', 'as' =>'cashiers.'], function() {
	      		Route::view('/', 'back.cashiers.index')->name('index');
	      		Route::post('datatable', 'CashierController@datatable')->name('datatable');
  		      	Route::get('create', 'CashierController@create')->name('create');
	      		Route::post('store', 'CashierController@store')->name('store');
	      		Route::get('edit/{id}', 'CashierController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'CashierController@update')->name('update');
	      		Route::post('status', 'CashierController@status')->name('status');
	        	Route::post('/delete', 'CashierController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'clients', 'as' =>'clients.'], function() {
	      		Route::view('/', 'back.clients.index')->name('index');
	      		Route::post('datatable', 'ClientController@datatable')->name('datatable');
  		      	Route::get('create', 'ClientController@create')->name('create');
	      		Route::post('store', 'ClientController@store')->name('store');
	      		Route::get('edit/{id}', 'ClientController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'ClientController@update')->name('update');
	      		Route::post('status', 'ClientController@status')->name('status');
	        	Route::post('/delete', 'ClientController@destroy')->name('destroy');
	    	});


		   	Route::group(['prefix'=>'money', 'as' =>'money.'], function() {
	      		Route::get('/', 'MoneyController@index')->name('index');
	      		Route::post('/store', 'MoneyController@store')->name('store');
	    	});

		   	Route::group(['prefix'=>'transactions', 'as' =>'transactions.'], function() {
	      		Route::view('/', 'back.transactions')->name('index');
	      		Route::post('/datatable', 'MoneyController@transactionsDatatable')->name('datatable');
			});
			
			Route::group(['prefix' => 'settings'], function(){
				Route::get('/', 'AdminController@settings')->name('settings.index');
				Route::post('/', 'AdminController@sportsCreate')->name('settings.sports.create');
				//Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

	   	});

	});	

	Route::get('/logout', 'Auth\LoginController@logout')->name('backstagelogout');
});

Route::get('/{any}', function () {
    return view('welcome');
})->where('any', '.*');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/back/dashboard.blade.php
@extends('layouts.back')
@section('title') Dashboard @stop

@section('style')
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Tableau de bord</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active">Tableau de bord</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
	</div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
<!-- sparkline chart -->
<script src="{{ asset('back/plugins/sparkline/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('back/js/dashboard4.js') }}"></script>
<!-- ============================================================== -->
<!-- Style switcher -->
<!-- ============================================================== -->
<script src="{{ asset('back/plugins/styleswitcher/jQuery.style.switcher.js') }}"></script>
@endsection

resources/views/back/money.blade.php
@extends('layouts.back')
@section('title') Versement/Retrait @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
    <link href="{{ asset('back/plugins/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Versement / Retrait</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item active">Versement / Retrait</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post"  action="{{ route('money.store') }}" id="money">
                            @csrf
                            <div class="form-body">
                                @include('includes.msg')
                                <div class="row">
                                    <div class="col-md-5 m-auto">
                                        <div class="form-group">
                                            <label class="control-label">Type
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <select class="select2 form-control" data-placeholder='' style="width: 100%; height:36px;" name="type">
                                                <option></option>
                                                <option value="0">Versement</option>
                                                <option value="1">Retrait</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">{{ $selectTitle }}
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <select class="select2 form-control" data-placeholder='' style="width: 100%; height:36px;" name="receiver_id">
                                                <option></option>
                                                @foreach($admins as $admin)
                                                    <option value="{{ $admin->id }}" {{ (old("receiver_id") != $admin->id ?: "selected") }}>{{ $admin->name() }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Montant
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input name="amount" type="text" value="{{ old('amount') }}" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-5 m-auto">
                                    	<div class="row">
                                    		<div class="col-6">
                                    			<a href="{{ route('admin.dashboard') }}" class="btn btn-outline-info">Annuler</a>
                                    		</div>
                                    		<div class="col-6 text-right">
                                    			<button type="submit" class="btn waves-effect waves-light btn-success">Valider</button>
                                    		</div>
                                    	</div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/jquery.validate.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/additional-methods.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/select2/dist/js/select2.full.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/js/form-validation.js') }}" type="text/javascript"></script>
@endsection

resources/views/back/transactions.blade.php
@extends('layouts.back')
@section('title') transactions @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
    <link href="{{ asset('back/plugins/bootstrap-switch/bootstrap-switch.min.css') }}" rel="stylesheet">
    <link href="{{ asset('back/plugins/toast-master/css/jquery.toast.css') }}" rel="stylesheet">
    <link href="{{ asset('back/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Transactions</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item active">Transactions</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="transactions" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Sender</th>
                                        <th>Receiver</th>
                                        <th>Amount</th>
                                        <th>Type</th>
                                        <th width="60">Date</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Sender</th>
                                        <th>Receiver</th>
                                        <th>Amount</th>
                                        <th>Type</th>
                                        <th width="60">Date</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('back/plugins/bootstrap-switch/bootstrap-switch.min.js') }}"></script>
    <script src="{{ asset('back/plugins/toast-master/js/jquery.toast.js') }}"></script>

    <script src="{{ asset('back/plugins/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ asset('back/plugins/sweetalert/jquery.sweet-alert.custom.js') }}"></script>
    <script src="{{ asset('back/plugins/datatables/date-euro.js') }}"></script>
    <script src="{{ asset('back/js/data-table.js') }}"></script>
    <script src="{{ asset('back/js/add-script.js') }}"></script>
@endsection