routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'role:client']], function(){
	Route::get('/home', 'HomeController@index')->name('user.home');
});

Route::group(['prefix' => 'backstage'], function(){

	Auth::routes();	

	Route::group(['middleware' => ['auth', 'role:super-admin|admin|cashier']], function(){

		Route::group(['namespace'=>'Admin'], function() {

			Route::get('/', 'DashboardController@index')->name('admin.dashboard');
			Route::get('check_email', 'AdminController@check_email')->name('admin.check_email');
			Route::get('check_username', 'AdminController@check_username')->name('admin.check_username');


			Route::group(['prefix' => 'account'], function(){
				Route::get('/', 'AdminController@account')->name('admin.account');
				Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

		   	Route::group(['prefix'=>'admins','middleware' => 'role:super-admin', 'as' =>'admins.'], function() {
	      		Route::view('/', 'back.admins.index')->name('index');
	      		Route::post('datatable', 'AdminController@datatable')->name('datatable');
  		      	Route::view('create', 'back.admins.create')->name('create');
	      		Route::post('store', 'AdminController@store')->name('store');
	      		Route::get('edit/{id}', 'AdminController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'AdminController@update')->name('update');
	      		Route::post('status', 'AdminController@status')->name('status');
	        	Route::post('/delete', 'AdminController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'cashiers','middleware' => 'role:super-admin|admin', 'as' =>'cashiers.'], function() {
	      		Route::view('/', 'back.cashiers.index')->name('index');
	      		Route::post('datatable', 'CashierController@datatable')->name('datatable');
  		      	Route::get('create', 'CashierController@create')->name('create');
	      		Route::post('store', 'CashierController@store')->name('store');
	      		Route::get('edit/{id}', 'CashierController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'CashierController@update')->name('update');
	      		Route::post('status', 'CashierController@status')->name('status');
	        	Route::post('/delete', 'CashierController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'clients', 'as' =>'clients.'], function() {
	      		Route::view('/', 'back.clients.index')->name('index');
	      		Route::post('datatable', 'ClientController@datatable')->name('datatable');
  		      	Route::get('create', 'ClientController@create')->name('create');
	      		Route::post('store', 'ClientController@store')->name('store');
	      		Route::get('edit/{id}', 'ClientController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'ClientController@update')->name('update');
	      		Route::post('status', 'ClientController@status')->name('status');
	        	Route::post('/delete', 'ClientController@destroy')->name('destroy');
	    	});


		   	Route::group(['prefix'=>'money', 'as' =>'money.'], function() {
	      		Route::get('/', 'MoneyController@index')->name('index');
	      		Route::post('/store', 'MoneyController@store')->name('store');
	    	});

		   	Route::group(['prefix'=>'transactions', 'as' =>'transactions.'], function() {
	      		Route::view('/', 'back.transactions')->name('index');
	      		Route::post('/datatable', 'MoneyController@transactionsDatatable')->name('datatable');
			});
			
			Route::group(['prefix' => 'settings'], function(){
				Route::get('/', 'AdminController@settings')->name('settings.index');
				Route::post('/', 'AdminController@sportsCreate')->name('settings.sports.create');
				//Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

	   	});

	});	

	Route::get('/logout', 'Auth\LoginController@logout')->name('backstagelogout');
});

Route::get('/{any}', function () {
    return view('welcome');
})->where('any', '.*');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Intervention\Image\Facades\Image;
use Illuminate\Validation\Rule;
use Yajra\DataTables\DataTables;
use App\Traits\CheckDB;
use App\User;
use Auth;

class ClientController extends Controller
{
	use CheckDB;

    public function check_email() {
        try {
            $request = request();
            return response()->json($this->checkDB_email($request));
        } catch (\Exception $e) {
            return response()->json(false);
        }
    }



    public function check_username() {
        try {
            $request = request();
            return response()->json($this->checkDB_username($request));
        } catch (\Exception $e) {
            return response()->json(false);
        }
    }

    public function edit($id) {
        $admins = null;
        if(Auth::user()->hasRole('super-admin')){
            $admins = User::withInactive()->role('admin')->get();
        }
        $user = User::withInactive()->role('client')->findOrFail($id);
        return view('back.cashiers.edit',compact('user','admins'));
    }

    public function updateClient() {

        $roles = array(
            'avatar' => 'mimes:jpeg,jpg,png',
            'first_name' => 'required',
            'last_name'  => 'required',
            'user_id'  => ['required', Rule::exists('users','id')],
            'email'  => 'required|email|unique:users,email,'.request('user_id')
        );

        if(request('password')){
            $roles["password"] = "required|between:6,20|confirmed";
            $roles["password_confirmation"] = "between:6,20";
        }

        $user = User::where('id',request('user_id'))->first();

        if($user){
            $user->first_name = request('first_name');
            $user->last_name = request('last_name');
            $user->email = request('email');
            if(request('username')){
                $user->username = request('username');
            }

            $user->save();

            return response()->json([
                "status" => 1,
                "code" => 200,
                "data" => $user,
                "message" => "updated user",
              ],200);
        }

    }

    public function update() {

        $roles = array(
            'avatar' => 'mimes:jpeg,jpg,png',
            'first_name' => 'required',
            'last_name'  => 'required',
            'user_id'  => ['required', Rule::exists('users','id')],
            'email'  => 'required|email|unique:users,email,'.request('user_id')
        );

        if(request('password')){
            $roles["password"] = "required|between:6,20|confirmed";
            $roles["password_confirmation"] = "between:6,20";
        }

        if(Auth::user()->hasRole('super-admin')){
            $roles["parent_id"] =  ['required', Rule::exists('users','id')];
        }


        request()->validate($roles);

        try {
            
            $admin = User::withInactive()->role('client')->findOrFail(request('user_id'));

            if(request('avatar')) {
                $file = request('avatar');
                $filename = time().'.'.$file->getClientOriginalExtension();
                $destinationPath = User::UPLOAD_DIR;
                $thumb_img = Image::make($file->getRealPath())->resize(70, null, function ($constraint) {
                    $constraint->aspectRatio();
                });
                $thumb_img->save($destinationPath.'thumbs/'.$filename);
                $file->move($destinationPath, $filename);
                File::delete(public_path(User::UPLOAD_DIR. 'thumbs/'.$admin->avatar));
                File::delete(public_path(User::UPLOAD_DIR. ''.$admin->avatar));
                $admin->avatar = $filename;
            }

            $admin->first_name = request('first_name');
            $admin->last_name = request('last_name');
            $admin->email = request('email');


            if(Auth::user()->hasRole('super-admin')){
                //super admin side
                if(User::find(request('parent_id'))->hasRole('admin')){
                    $admin->parent_id = request('parent_id');
                }else{
                    abort(500,"User parent error");
                }
            }else{
                //admin side (is connected)
                $admin->parent_id = Auth::user()->id;
            }  

            if(request('password')) 
                $admin->password = Hash::make(request('password'));
            $admin->save();

            if (request()->ajax() || request()->wantsJson()) {
                return response()->json([
                    'status'=>true,
                    'data'=>$admin,
                    'message'=>'Client Updated',
                    'error'=> null
                ],200, [], JSON_NUMERIC_CHECK);
            }


            return redirect()->back()
                ->with('success','Le cassiére a été modifié avec succès'); 

        } catch (\Exception $e) {

            if (request()->ajax() || request()->wantsJson()) {
                return response()->json([
                    'status'=>false,
                    'data'=>null,
                    'message'=>$e->getMessage(),
                    'error'=> null
                ],412);
            }

            return redirect()->back()
                ->with('error','Un erreur s\'est produite, Le cassiére n\'était pas modifiée. Merci de réessayer.')->withInput(); 
        } 
    }

    public function create() {

        $admins = null;
        if(Auth::user()->hasRole('super-admin')){
            $admins = User::withInactive()->role('admin')->get();
        }
        
        return view('back.clients.create',compact('admins'));
    }

    public function store() {

        $roles = array(
            'avatar' => 'mimes:jpeg,jpg,png',
            'first_name' => 'required',
            'last_name'  => 'required',
            'email'  => 'required|email|unique:users,email',
            'username'  => 'required|unique:users,username',
            'password'  => 'required|between:6,20|confirmed',
            'password_confirmation'  => 'required|between:6,20'
        );

        if(Auth::user()->hasRole('super-admin')){
            $roles["parent_id"] =  ['required', Rule::exists('users','id')];
        }

        request()->validate($roles);


        try {
            
            $admin = new User();

            if(request('avatar')) {
                $file = request('avatar');
                $filename = time().'.'.$file->getClientOriginalExtension();
                $destinationPath = User::UPLOAD_DIR;
                $thumb_img = Image::make($file->getRealPath())->resize(70, null, function ($constraint) {
                    $constraint->aspectRatio();
                });
                $thumb_img->save($destinationPath.'thumbs/'.$filename);
                $file->move($destinationPath, $filename);
                File::delete(public_path(User::UPLOAD_DIR. 'thumbs/'.$admin->avatar));
                File::delete(public_path(User::UPLOAD_DIR. ''.$admin->avatar));
                $admin->avatar = $filename;
            }

            $admin->first_name = request('first_name');
            $admin->last_name = request('last_name');
            $admin->email = request('email');
            $admin->username = request('username');
            $admin->password = Hash::make(request('password'));

            
            if(Auth::user()->hasRole('super-admin')){
                //super admin side
                if(User::find(request('parent_id'))->hasRole('admin')){
                    $admin->parent_id = request('parent_id');
                }else{
                    abort(500,"User parent error");
                }
            }else{
                //admin side (is connected)
                $admin->parent_id = Auth::user()->id;
            }   

            $admin->save();
            $admin->assignRole('client');

            if (request()->ajax() || request()->wantsJson()) {
                return response()->json([
                    'status'=>true,
                    'data'=>$admin,
                    'message'=>'Client Created',
                    'error'=> null
                ],200, [], JSON_NUMERIC_CHECK);
            }
            
            return redirect()->back()
                ->with('success','Le client a été ajouté avec succès'); 

        } catch (\Exception $e) {

            if (request()->ajax() || request()->wantsJson()) {
                return response()->json([
                    'status'=>false,
                    'data'=>null,
                    'message'=>$e->getMessage(),
                    'error'=> null
                ],412);
            }

            return redirect()->back()
                ->with('error','Un erreur s\'est produite, Le client  n\'était pas ajouté. Merci de réessayer.')->withInput(); 
        } 

    }

    public function datatable()
    {
    	$role = null;
        if(Auth::user()->hasRole('super-admin')){
        	$role = "super-admin";
            $admins = User::withInactive()->role('client')->get();
        }else if(Auth::user()->hasRole('admin')){
        	$role = "admin";
        	$parents = User::withInactive()->where('parent_id', Auth::user()->id)->role('cashier')->pluck('id');
            $admins = User::withInactive()->whereIn('parent_id',$parents)->role('client')->get();
        }else{
        	$role = "cashier";
        	$admins = User::withInactive()->where('parent_id', Auth::user()->id)->role('client')->get();
        }
        
        $admins->makeVisible('money');

        return DataTables::of($admins)
            ->editColumn('avatar', function($admin) {
                return '<img src="'.$admin->presentAvatar(true).'" class="img-circle" style="width:40px; height:40px"/>';
            })

resources/views/back/clients/create.blade.php
@extends('layouts.back')
@section('title') Ajouter cassiére @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
    <link href="{{ asset('back/plugins/select2/dist/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Ajouter cassiére</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item"><a href="{{ route('cashiers.index') }}">Cassiéres</a></li>
                <li class="breadcrumb-item active">Ajouter cassiére</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post"  action="{{ route('cashiers.store') }}" id="cashier_create" enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                @include('includes.msg')
                                <div class="row">
                                    <div class="col-md-4">
                                        @hasanyrole('super-admin')
                                        <div class="form-group">
                                            <label class="control-label">Admin
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <select class="select2 form-control" data-placeholder='Select Admin' style="width: 100%; height:36px;" name="parent_id">
                                                <option></option>
                                                @foreach($admins as $admin)
                                                    <option value="{{ $admin->id }}" {{ (old("parent_id") != $admin->id ?: "selected") }}>{{ $admin->name() }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Cassiéres
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <select class="select2 form-control" data-placeholder='Select Admin' style="width: 100%; height:36px;" name="parent_id">
                                                <option></option>
                                                @foreach($admins as $admin)
                                                    <option value="{{ $admin->id }}" {{ (old("parent_id") != $admin->id ?: "selected") }}>{{ $admin->name() }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                         @endhasrole
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <label class="control-label">Avatar</label>
                                            </div>
                                            <div class="col-sm-12">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="{{ asset('back/uploads/avatar.png') }}" class="profile-pic" /> 
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="width: 100%; max-height: 150px;"> </div>
                                                    <div>
                                                        <span class="btn red btn-outline btn-file">
                                                            <span class="fileinput-new btn waves-light btn-primary"> Choisir image </span>
                                                            <span class="fileinput-exists btn waves-light btn-outline-warning"> Changer </span>
                                                            <input type="file" name="avatar" accept="image/png,image/jpg,image/jpeg"> </span>
                                                        <a href="javascript:;" class="btn waves-light btn-danger fileinput-exists" data-dismiss="fileinput"> Supprimer </a>
                                                    </div>
                                                </div>
                                                <div class="clearfix margin-top-10">
                                                    <span class="label label-success">NOTE!</span> JPG, PNG seulement. 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Nom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="first_name" data-required="1" class="form-control"  value="{{ old('first_name') }}" /> 
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Prénom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="last_name" value="{{ old('last_name') }}" data-required="1" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Email
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input name="email" type="text" value="{{ old('email') }}" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Username</label>
                                            <input name="username" type="text" id="username" value="{{ old('username') }}" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Mot de passe
                                            </label>
                                            <input name="password" type="password" id="password" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Confirmer mot de passe
                                            </label>
                                            <input name="password_confirmation" type="password" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-7"></div>
                                    <div class="col-md-4">
                                        <a href="{{ route('cashiers.index') }}" class="btn btn-outline-info">Annuler</a>
                                        <button type="submit" class="btn waves-effect waves-light btn-success">Ajouter</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/jquery.validate.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/additional-methods.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/select2/dist/js/select2.full.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/js/form-validation.js') }}" type="text/javascript"></script>
@endsection

resources/views/back/clients/index.blade.php
@extends('layouts.back')
@section('title') clients @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
    <link href="{{ asset('back/plugins/bootstrap-switch/bootstrap-switch.min.css') }}" rel="stylesheet">
    <link href="{{ asset('back/plugins/toast-master/css/jquery.toast.css') }}" rel="stylesheet">
    <link href="{{ asset('back/plugins/sweetalert/sweetalert.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Clients</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item active">Clients</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
            	<a href="{{ route('clients.create') }}" class="btn btn-success rounded-0">Nouveau client</a>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="clients-table" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%" data-user="{{ Auth::user()->getRoleNames() }}">
                                <thead>
                                    <tr>
                                        <th>Avatar</th>
                                        <th>Nom</th>
                                        <th>Prénom</th>
                                        <th>Parent</th>
                                        <th>Email</th>
                                        <th>Money</th>
                                        <th width="60">Statut</th>
                                        <th width="60">Date de création</th>
                                        <th width="60">Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Avatar</th>
                                        <th>Nom</th>
                                        <th>Prénom</th>
                                        <th>Parent</th>
                                        <th>Email</th>
                                        <th>Money</th>
                                        <th>Statut</th>
                                        <th>Date de création</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('back/plugins/bootstrap-switch/bootstrap-switch.min.js') }}"></script>
    <script src="{{ asset('back/plugins/toast-master/js/jquery.toast.js') }}"></script>

    <script src="{{ asset('back/plugins/sweetalert/sweetalert.min.js') }}"></script>
    <script src="{{ asset('back/plugins/sweetalert/jquery.sweet-alert.custom.js') }}"></script>
    <script src="{{ asset('back/plugins/datatables/date-euro.js') }}"></script>
    <script src="{{ asset('back/js/data-table.js') }}"></script>
    <script src="{{ asset('back/js/add-script.js') }}"></script>
@endsection