routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'role:client']], function(){
	Route::get('/home', 'HomeController@index')->name('user.home');
});

Route::group(['prefix' => 'backstage'], function(){

	Auth::routes();	

	Route::group(['middleware' => ['auth', 'role:super-admin|admin|cashier']], function(){

		Route::group(['namespace'=>'Admin'], function() {

			Route::get('/', 'DashboardController@index')->name('admin.dashboard');
			Route::get('check_email', 'AdminController@check_email')->name('admin.check_email');
			Route::get('check_username', 'AdminController@check_username')->name('admin.check_username');


			Route::group(['prefix' => 'account'], function(){
				Route::get('/', 'AdminController@account')->name('admin.account');
				Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

		   	Route::group(['prefix'=>'admins','middleware' => 'role:super-admin', 'as' =>'admins.'], function() {
	      		Route::view('/', 'back.admins.index')->name('index');
	      		Route::post('datatable', 'AdminController@datatable')->name('datatable');
  		      	Route::view('create', 'back.admins.create')->name('create');
	      		Route::post('store', 'AdminController@store')->name('store');
	      		Route::get('edit/{id}', 'AdminController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'AdminController@update')->name('update');
	      		Route::post('status', 'AdminController@status')->name('status');
	        	Route::post('/delete', 'AdminController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'cashiers','middleware' => 'role:super-admin|admin', 'as' =>'cashiers.'], function() {
	      		Route::view('/', 'back.cashiers.index')->name('index');
	      		Route::post('datatable', 'CashierController@datatable')->name('datatable');
  		      	Route::get('create', 'CashierController@create')->name('create');
	      		Route::post('store', 'CashierController@store')->name('store');
	      		Route::get('edit/{id}', 'CashierController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'CashierController@update')->name('update');
	      		Route::post('status', 'CashierController@status')->name('status');
	        	Route::post('/delete', 'CashierController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'clients', 'as' =>'clients.'], function() {
	      		Route::view('/', 'back.clients.index')->name('index');
	      		Route::post('datatable', 'ClientController@datatable')->name('datatable');
  		      	Route::get('create', 'ClientController@create')->name('create');
	      		Route::post('store', 'ClientController@store')->name('store');
	      		Route::get('edit/{id}', 'ClientController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'ClientController@update')->name('update');
	      		Route::post('status', 'ClientController@status')->name('status');
	        	Route::post('/delete', 'ClientController@destroy')->name('destroy');
	    	});


		   	Route::group(['prefix'=>'money', 'as' =>'money.'], function() {
	      		Route::get('/', 'MoneyController@index')->name('index');
	      		Route::post('/store', 'MoneyController@store')->name('store');
	    	});

		   	Route::group(['prefix'=>'transactions', 'as' =>'transactions.'], function() {
	      		Route::view('/', 'back.transactions')->name('index');
	      		Route::post('/datatable', 'MoneyController@transactionsDatatable')->name('datatable');
			});
			
			Route::group(['prefix' => 'settings'], function(){
				Route::get('/', 'AdminController@settings')->name('settings.index');
				Route::post('/', 'AdminController@sportsCreate')->name('settings.sports.create');
				//Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

	   	});

	});	

	Route::get('/logout', 'Auth\LoginController@logout')->name('backstagelogout');
});

Route::get('/{any}', function () {
    return view('welcome');
})->where('any', '.*');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/includes/msg.blade.php
@if (session('error'))
   <div class="alert alert-danger alertadd">
       {!! session('error') !!}
   </div>
@endif

@if (session('success'))
   <div class="alert alert-success alertadd">
       {!! session('success') !!}
   </div>
@endif

@if(count($errors) > 0)
   <div class="alert alert-danger alertadd">
      @foreach($errors->all() as $error)
         <p>{{ $error }}</p>
      @endforeach
   </div>
@endif

<div class="alert alert-danger hide">
   <button class="close" data-close="alert"></button> Vous avez des erreurs de formulaire. Veuillez vérifier ci-dessous. 
</div>
<div class="alert alert-success hide">
   <button class="close" data-close="alert"></button> La validation de votre formulaire est réussie! 
</div>

resources/views/includes/sidebar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        @if( Auth::check() ) 
        <div class="user-profile">
            <!-- User profile image -->
            <div class="profile-img"> 
                <img  src="{{ Auth::user()->presentAvatar(true) }}"/>
            </div>
            <!-- User profile text--> 
            <div class="profile-text"> 
                <h5> {{ Auth::user()->name() }}</h5>
                <a href="#" class="dropdown-toggle u-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><i class="mdi mdi-settings"></i></a>
                <a href="{{ route('backstagelogout') }}" class="" data-toggle="tooltip" title="Déconnexion"><i class="mdi mdi-power"></i></a>
                <div class="dropdown-menu animated flipInY">
                <!-- text--> 
                <a href="{{ route('admin.account') }}" class="dropdown-item"><i class="ti-user"></i> Mon compte</a>
                <!-- text--> 
                <div class="dropdown-divider"></div>
                <!-- text-->  
                <a href="{{ route('backstagelogout') }}" class="dropdown-item"><i class="fa fa-power-off"></i> Déconnexion</a>
                <!-- text-->  
                </div>
            </div> 
        </div>
         @endif
        <!-- End User profile text-->
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-devider"></li>
                <li class="{{ active_route('admin.dashboard') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('admin.dashboard') }}" href="{{ route('admin.dashboard') }}">
                        <i class="mdi mdi-gauge"></i>
                        <span class="hide-menu">Tableau de bord </span>
                    </a>
                </li>
                @hasrole('super-admin')
                <li class="{{ active_route('admins.*') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('admins.*') }}" href="{{ route('admins.index') }}">
                        <i class="mdi mdi-account-settings-variant"></i>
                        <span class="hide-menu">Admins</span>
                    </a>
                </li>
                @endhasrole
                @hasanyrole('super-admin|admin')
                <li class="{{ active_route('cashiers.*') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('cashiers.*') }}" href="{{ route('cashiers.index') }}">
                        <i class="mdi mdi-account-key"></i>
                        <span class="hide-menu">Caissières</span>
                    </a>
                </li>
                @endhasanyrole
                @hasanyrole('super-admin|admin|cashier')
                <li class="{{ active_route('clients.*') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('clients.*') }}" href="{{ route('clients.index') }}">
                        <i class="mdi mdi-account"></i>
                        <span class="hide-menu">Clients</span>
                    </a>
                </li>
                @endhasanyrole


                <li class="{{ active_route('money.index') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('money.index') }}" href="{{ route('money.index') }}">
                        <i class="mdi mdi-currency-usd"></i>
                        <span class="hide-menu">Versement/Retrait</span>
                    </a>
                </li>

                <li class="{{ active_route('transactions.index') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('transactions.index') }}" href="{{ route('transactions.index') }}">
                        <i class="mdi mdi-swap-horizontal"></i>
                        <span class="hide-menu">Transactions </span>
                    </a>
                </li>
                @hasrole('super-admin')
                <li class="{{ active_route('settings.*') }}"> 
                    <a class="waves-effect waves-dark {{ active_route('settings.*') }}" href="{{ route('settings.index') }}">
                        <i class="mdi mdi-settings"></i>
                        <span class="hide-menu">Settings</span>
                    </a>
                </li>
                @endhasrole
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>