routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth', 'role:client']], function(){
	Route::get('/home', 'HomeController@index')->name('user.home');
});

Route::group(['prefix' => 'backstage'], function(){

	Auth::routes();	

	Route::group(['middleware' => ['auth', 'role:super-admin|admin|cashier']], function(){

		Route::group(['namespace'=>'Admin'], function() {

			Route::get('/', 'DashboardController@index')->name('admin.dashboard');
			Route::get('check_email', 'AdminController@check_email')->name('admin.check_email');
			Route::get('check_username', 'AdminController@check_username')->name('admin.check_username');


			Route::group(['prefix' => 'account'], function(){
				Route::get('/', 'AdminController@account')->name('admin.account');
				Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

		   	Route::group(['prefix'=>'admins','middleware' => 'role:super-admin', 'as' =>'admins.'], function() {
	      		Route::view('/', 'back.admins.index')->name('index');
	      		Route::post('datatable', 'AdminController@datatable')->name('datatable');
  		      	Route::view('create', 'back.admins.create')->name('create');
	      		Route::post('store', 'AdminController@store')->name('store');
	      		Route::get('edit/{id}', 'AdminController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'AdminController@update')->name('update');
	      		Route::post('status', 'AdminController@status')->name('status');
	        	Route::post('/delete', 'AdminController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'cashiers','middleware' => 'role:super-admin|admin', 'as' =>'cashiers.'], function() {
	      		Route::view('/', 'back.cashiers.index')->name('index');
	      		Route::post('datatable', 'CashierController@datatable')->name('datatable');
  		      	Route::get('create', 'CashierController@create')->name('create');
	      		Route::post('store', 'CashierController@store')->name('store');
	      		Route::get('edit/{id}', 'CashierController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'CashierController@update')->name('update');
	      		Route::post('status', 'CashierController@status')->name('status');
	        	Route::post('/delete', 'CashierController@destroy')->name('destroy');
	    	});

		   	Route::group(['prefix'=>'clients', 'as' =>'clients.'], function() {
	      		Route::view('/', 'back.clients.index')->name('index');
	      		Route::post('datatable', 'ClientController@datatable')->name('datatable');
  		      	Route::get('create', 'ClientController@create')->name('create');
	      		Route::post('store', 'ClientController@store')->name('store');
	      		Route::get('edit/{id}', 'ClientController@edit')->name('edit')->where('id', '[0-9]+');
	      		Route::post('update', 'ClientController@update')->name('update');
	      		Route::post('status', 'ClientController@status')->name('status');
	        	Route::post('/delete', 'ClientController@destroy')->name('destroy');
	    	});


		   	Route::group(['prefix'=>'money', 'as' =>'money.'], function() {
	      		Route::get('/', 'MoneyController@index')->name('index');
	      		Route::post('/store', 'MoneyController@store')->name('store');
	    	});

		   	Route::group(['prefix'=>'transactions', 'as' =>'transactions.'], function() {
	      		Route::view('/', 'back.transactions')->name('index');
	      		Route::post('/datatable', 'MoneyController@transactionsDatatable')->name('datatable');
			});
			
			Route::group(['prefix' => 'settings'], function(){
				Route::get('/', 'AdminController@settings')->name('settings.index');
				Route::post('/', 'AdminController@sportsCreate')->name('settings.sports.create');
				//Route::post('update', 'AdminController@accountUpdate')->name('admin.account.update');
			});

	   	});

	});	

	Route::get('/logout', 'Auth\LoginController@logout')->name('backstagelogout');
});

Route::get('/{any}', function () {
    return view('welcome');
})->where('any', '.*');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/back/admins/account.blade.php
@extends('layouts.back')
@section('title') Account @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Mon compte</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item active">Mon compte</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post"  action="{{ route('admin.account.update') }}" id="admin_account"  data-id="{{ $admin->id }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                @include('includes.msg')
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <label class="control-label">Avatar</label>
                                            </div>
                                            <div class="col-sm-12">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="{{ Auth::user()->presentAvatar() }}" class="profile-pic" /> 
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="width: 100%; max-height: 150px;"> </div>
                                                    <div>
                                                        <span class="btn red btn-outline btn-file">
                                                            <span class="fileinput-new btn waves-light btn-primary"> Choisir image </span>
                                                            <span class="fileinput-exists btn waves-light btn-outline-warning"> Changer </span>
                                                            <input type="file" name="avatar" accept="image/png,image/jpg,image/jpeg"> </span>
                                                        <a href="javascript:;" class="btn waves-light btn-danger fileinput-exists" data-dismiss="fileinput"> Supprimer </a>
                                                    </div>
                                                </div>
                                                <div class="clearfix margin-top-10">
                                                    <span class="label label-success">NOTE!</span> JPG, PNG seulement. 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Nom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="first_name" data-required="1" class="form-control"  value="{{ old('first_name', $admin->first_name) }}" /> 
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Prénom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="last_name" value="{{ old('last_name', $admin->last_name) }}" data-required="1" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Email
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input name="email" type="text" value="{{ old('email', $admin->email) }}" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Username
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="username" value="{{ old('username', $admin->username) }}" data-required="1" class="form-control" />
                                        </div>
                                        <h5 class="form-section">Optionnel</h5>
                                        <hr>
                                        <div class="form-group">
                                            <label class="control-label">Mot de passe
                                            </label>
                                            <input name="password" type="password" id="password" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Confirmer mot de passe
                                            </label>
                                            <input name="password_confirmation" type="password" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-7"></div>
                                    <div class="col-md-4">
                                        <a href="{{ route('admin.dashboard') }}" class="btn btn-outline-info">Annuler</a>
                                        <button type="submit" class="btn waves-effect waves-light btn-warning">Modifier</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/jquery.validate.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/additional-methods.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/js/form-validation.js') }}" type="text/javascript"></script>
@endsection

resources/views/back/admins/create.blade.php
@extends('layouts.back')
@section('title') Ajouter Admin @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Ajouter Admin</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admins.index') }}">Admins</a></li>
                <li class="breadcrumb-item active">Ajouter Admin</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post"  action="{{ route('admins.store') }}" id="admin_create" enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                @include('includes.msg')
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <label class="control-label">Avatar</label>
                                            </div>
                                            <div class="col-sm-12">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="{{ asset('back/uploads/avatar.png') }}" class="profile-pic" /> 
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="width: 100%; max-height: 150px;"> </div>
                                                    <div>
                                                        <span class="btn red btn-outline btn-file">
                                                            <span class="fileinput-new btn waves-light btn-primary"> Choisir image </span>
                                                            <span class="fileinput-exists btn waves-light btn-outline-warning"> Changer </span>
                                                            <input type="file" name="avatar" accept="image/png,image/jpg,image/jpeg"> </span>
                                                        <a href="javascript:;" class="btn waves-light btn-danger fileinput-exists" data-dismiss="fileinput"> Supprimer </a>
                                                    </div>
                                                </div>
                                                <div class="clearfix margin-top-10">
                                                    <span class="label label-success">NOTE!</span> JPG, PNG seulement. 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Nom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="first_name" data-required="1" class="form-control"  value="{{ old('first_name') }}" /> 
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Prénom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="last_name" value="{{ old('last_name') }}" data-required="1" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Email
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input name="email" type="text" value="{{ old('email') }}" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Username</label>
                                            <input name="username" type="text" id="username" value="{{ old('username') }}" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Mot de passe
                                            </label>
                                            <input name="password" type="password" id="password" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Confirmer mot de passe
                                            </label>
                                            <input name="password_confirmation" type="password" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-7"></div>
                                    <div class="col-md-4">
                                        <a href="{{ route('admins.index') }}" class="btn btn-outline-info">Annuler</a>
                                        <button type="submit" class="btn waves-effect waves-light btn-success">Ajouter</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/jquery.validate.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/additional-methods.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/js/form-validation.js') }}" type="text/javascript"></script>
@endsection

resources/views/back/admins/edit.blade.php
@extends('layouts.back')
@section('title') Modifier Admin @stop

@section('style')
    <link href="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.css') }}" id="theme" rel="stylesheet">
@endsection

@section('content')
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Modifier Admin</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admins.index') }}">Admins</a></li>
                <li class="breadcrumb-item active">Modifier Admin</li>
            </ol>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post"  action="{{ route('admins.update') }}" id="admin_edit"  data-id="{{ $user->id }}"  enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                @include('includes.msg')
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <div class="col-sm-12">
                                                <label class="control-label">Avatar</label>
                                            </div>
                                            <div class="col-sm-12">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                                        <img src="{{ $user->presentAvatar() }}" class="profile-pic" /> 
                                                    </div>
                                                    <div class="fileinput-preview fileinput-exists thumbnail" style="width: 100%; max-height: 150px;"> </div>
                                                    <div>
                                                        <span class="btn red btn-outline btn-file">
                                                            <span class="fileinput-new btn waves-light btn-primary"> Choisir image </span>
                                                            <span class="fileinput-exists btn waves-light btn-outline-warning"> Changer </span>
                                                            <input type="file" name="avatar" accept="image/png,image/jpg,image/jpeg"> </span>
                                                        <a href="javascript:;" class="btn waves-light btn-danger fileinput-exists" data-dismiss="fileinput"> Supprimer </a>
                                                    </div>
                                                </div>
                                                <div class="clearfix margin-top-10">
                                                    <span class="label label-success">NOTE!</span> JPG, PNG seulement. 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label class="control-label">Nom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="first_name" data-required="1" class="form-control"  value="{{ old('first_name', $user->first_name) }}" /> 
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Prénom
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input type="text" name="last_name" value="{{ old('last_name', $user->last_name) }}" data-required="1" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Email
                                                <span class="text-danger"> * </span>
                                            </label>
                                            <input name="email" type="text" value="{{ old('email', $user->email) }}" class="form-control" />
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <h5 class="form-section">Optionnel</h5>
                                        <hr>
                                        <div class="form-group">
                                            <label class="control-label">Mot de passe
                                            </label>
                                            <input name="password" type="password" id="password" class="form-control" />
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label">Confirmer mot de passe
                                            </label>
                                            <input name="password_confirmation" type="password" class="form-control" />
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" name="user_id" value="{{ $user->id }}">
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-7"></div>
                                    <div class="col-md-4">
                                        <a href="{{ route('admins.index') }}" class="btn btn-outline-info">Annuler</a>
                                        <button type="submit" class="btn waves-effect waves-light btn-warning">Modifier</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
@endsection


@section('script')
    <script src="{{ asset('back/plugins/bootstrap-fileinput/bootstrap-fileinput.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/jquery.validate.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/plugins/jquery-validation/js/additional-methods.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('back/js/form-validation.js') }}" type="text/javascript"></script>
@endsection